# Generated by Django 4.1.5 on 2023-02-01 12:29

from django.db import migrations, models


# NEVER modify the migration directly, always modify the models.py first then run the 'makemigrations' command in the terminal
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
    ]
